services:
  api:
    container_name: api2
    build:
      context: ./Gateway
      dockerfile: /DOCKERFILE
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mynetwork
    depends_on:
      - rabbitmq2
    restart: always

  emailmicroservice:
    container_name: emailmicroservice
    build:
      context: ./EmailMicroservice
      dockerfile: /DOCKERFILE
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mynetwork
    depends_on:
      - rabbitmq2
    restart: always
    
  
  rabbitmq2:
    image: "rabbitmq:management"
    container_name: rabbitmq2
    restart: always
    networks:
      - mynetwork 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    

volumes:
  rabbitmq2_data:

networks:
  mynetwork:  
    driver: bridge