FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

COPY ./NotificationStatusMicroserviceervice/bin/Release/net8.0/linux-x64/publish/ .

ENTRYPOINT ["dotnet", "NotificationStatusMicroserviceervice.dll"]